/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReservasRouteImport } from './routes/reservas'
import { Route as ResenasRouteImport } from './routes/resenas'
import { Route as PromocionesRouteImport } from './routes/promociones'
import { Route as PreguntasRouteImport } from './routes/preguntas'
import { Route as MisPedidosRouteImport } from './routes/mis-pedidos'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HorariosRouteImport } from './routes/horarios'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as EventosRouteImport } from './routes/eventos'
import { Route as ConozcanosRouteImport } from './routes/conozcanos'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as PedidoIdRouteImport } from './routes/pedido.$id'
import { Route as AdminUsuariosRouteImport } from './routes/admin.usuarios'
import { Route as AdminResenasRouteImport } from './routes/admin.resenas'
import { Route as AdminRedesRouteImport } from './routes/admin.redes'
import { Route as AdminPromocionesRouteImport } from './routes/admin.promociones'
import { Route as AdminPreguntasRouteImport } from './routes/admin.preguntas'
import { Route as AdminPedidosRouteImport } from './routes/admin.pedidos'
import { Route as AdminMenuRouteImport } from './routes/admin.menu'
import { Route as AdminLenguajesRouteImport } from './routes/admin.lenguajes'
import { Route as AdminInicioRouteImport } from './routes/admin.inicio'
import { Route as AdminInformacionRouteImport } from './routes/admin.informacion'
import { Route as AdminHorarioRouteImport } from './routes/admin.horario'
import { Route as AdminFiltrosRouteImport } from './routes/admin.filtros'
import { Route as AdminEventosRouteImport } from './routes/admin.eventos'
import { Route as AdminConozcanosRouteImport } from './routes/admin.conozcanos'
import { Route as AdminCategoriasRouteImport } from './routes/admin.categorias'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReservasRoute = ReservasRouteImport.update({
  id: '/reservas',
  path: '/reservas',
  getParentRoute: () => rootRouteImport,
} as any)
const ResenasRoute = ResenasRouteImport.update({
  id: '/resenas',
  path: '/resenas',
  getParentRoute: () => rootRouteImport,
} as any)
const PromocionesRoute = PromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => rootRouteImport,
} as any)
const PreguntasRoute = PreguntasRouteImport.update({
  id: '/preguntas',
  path: '/preguntas',
  getParentRoute: () => rootRouteImport,
} as any)
const MisPedidosRoute = MisPedidosRouteImport.update({
  id: '/mis-pedidos',
  path: '/mis-pedidos',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HorariosRoute = HorariosRouteImport.update({
  id: '/horarios',
  path: '/horarios',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const EventosRoute = EventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => rootRouteImport,
} as any)
const ConozcanosRoute = ConozcanosRouteImport.update({
  id: '/conozcanos',
  path: '/conozcanos',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const PedidoIdRoute = PedidoIdRouteImport.update({
  id: '/pedido/$id',
  path: '/pedido/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsuariosRoute = AdminUsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => AdminRoute,
} as any)
const AdminResenasRoute = AdminResenasRouteImport.update({
  id: '/resenas',
  path: '/resenas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRedesRoute = AdminRedesRouteImport.update({
  id: '/redes',
  path: '/redes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPromocionesRoute = AdminPromocionesRouteImport.update({
  id: '/promociones',
  path: '/promociones',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPreguntasRoute = AdminPreguntasRouteImport.update({
  id: '/preguntas',
  path: '/preguntas',
  getParentRoute: () => AdminRoute,
} as any)
const AdminPedidosRoute = AdminPedidosRouteImport.update({
  id: '/pedidos',
  path: '/pedidos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMenuRoute = AdminMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLenguajesRoute = AdminLenguajesRouteImport.update({
  id: '/lenguajes',
  path: '/lenguajes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInicioRoute = AdminInicioRouteImport.update({
  id: '/inicio',
  path: '/inicio',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInformacionRoute = AdminInformacionRouteImport.update({
  id: '/informacion',
  path: '/informacion',
  getParentRoute: () => AdminRoute,
} as any)
const AdminHorarioRoute = AdminHorarioRouteImport.update({
  id: '/horario',
  path: '/horario',
  getParentRoute: () => AdminRoute,
} as any)
const AdminFiltrosRoute = AdminFiltrosRouteImport.update({
  id: '/filtros',
  path: '/filtros',
  getParentRoute: () => AdminRoute,
} as any)
const AdminEventosRoute = AdminEventosRouteImport.update({
  id: '/eventos',
  path: '/eventos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminConozcanosRoute = AdminConozcanosRouteImport.update({
  id: '/conozcanos',
  path: '/conozcanos',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCategoriasRoute = AdminCategoriasRouteImport.update({
  id: '/categorias',
  path: '/categorias',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/conozcanos': typeof ConozcanosRoute
  '/eventos': typeof EventosRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/preguntas': typeof PreguntasRoute
  '/promociones': typeof PromocionesRoute
  '/resenas': typeof ResenasRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/conozcanos': typeof AdminConozcanosRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/filtros': typeof AdminFiltrosRoute
  '/admin/horario': typeof AdminHorarioRoute
  '/admin/informacion': typeof AdminInformacionRoute
  '/admin/inicio': typeof AdminInicioRoute
  '/admin/lenguajes': typeof AdminLenguajesRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/preguntas': typeof AdminPreguntasRoute
  '/admin/promociones': typeof AdminPromocionesRoute
  '/admin/redes': typeof AdminRedesRoute
  '/admin/resenas': typeof AdminResenasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/conozcanos': typeof ConozcanosRoute
  '/eventos': typeof EventosRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/preguntas': typeof PreguntasRoute
  '/promociones': typeof PromocionesRoute
  '/resenas': typeof ResenasRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/conozcanos': typeof AdminConozcanosRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/filtros': typeof AdminFiltrosRoute
  '/admin/horario': typeof AdminHorarioRoute
  '/admin/informacion': typeof AdminInformacionRoute
  '/admin/inicio': typeof AdminInicioRoute
  '/admin/lenguajes': typeof AdminLenguajesRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/preguntas': typeof AdminPreguntasRoute
  '/admin/promociones': typeof AdminPromocionesRoute
  '/admin/redes': typeof AdminRedesRoute
  '/admin/resenas': typeof AdminResenasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/checkout': typeof CheckoutRoute
  '/conozcanos': typeof ConozcanosRoute
  '/eventos': typeof EventosRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/horarios': typeof HorariosRoute
  '/login': typeof LoginRoute
  '/menu': typeof MenuRoute
  '/mis-pedidos': typeof MisPedidosRoute
  '/preguntas': typeof PreguntasRoute
  '/promociones': typeof PromocionesRoute
  '/resenas': typeof ResenasRoute
  '/reservas': typeof ReservasRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/categorias': typeof AdminCategoriasRoute
  '/admin/conozcanos': typeof AdminConozcanosRoute
  '/admin/eventos': typeof AdminEventosRoute
  '/admin/filtros': typeof AdminFiltrosRoute
  '/admin/horario': typeof AdminHorarioRoute
  '/admin/informacion': typeof AdminInformacionRoute
  '/admin/inicio': typeof AdminInicioRoute
  '/admin/lenguajes': typeof AdminLenguajesRoute
  '/admin/menu': typeof AdminMenuRoute
  '/admin/pedidos': typeof AdminPedidosRoute
  '/admin/preguntas': typeof AdminPreguntasRoute
  '/admin/promociones': typeof AdminPromocionesRoute
  '/admin/redes': typeof AdminRedesRoute
  '/admin/resenas': typeof AdminResenasRoute
  '/admin/usuarios': typeof AdminUsuariosRoute
  '/pedido/$id': typeof PedidoIdRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/checkout'
    | '/conozcanos'
    | '/eventos'
    | '/forgot-password'
    | '/horarios'
    | '/login'
    | '/menu'
    | '/mis-pedidos'
    | '/preguntas'
    | '/promociones'
    | '/resenas'
    | '/reservas'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/categorias'
    | '/admin/conozcanos'
    | '/admin/eventos'
    | '/admin/filtros'
    | '/admin/horario'
    | '/admin/informacion'
    | '/admin/inicio'
    | '/admin/lenguajes'
    | '/admin/menu'
    | '/admin/pedidos'
    | '/admin/preguntas'
    | '/admin/promociones'
    | '/admin/redes'
    | '/admin/resenas'
    | '/admin/usuarios'
    | '/pedido/$id'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/conozcanos'
    | '/eventos'
    | '/forgot-password'
    | '/horarios'
    | '/login'
    | '/menu'
    | '/mis-pedidos'
    | '/preguntas'
    | '/promociones'
    | '/resenas'
    | '/reservas'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/categorias'
    | '/admin/conozcanos'
    | '/admin/eventos'
    | '/admin/filtros'
    | '/admin/horario'
    | '/admin/informacion'
    | '/admin/inicio'
    | '/admin/lenguajes'
    | '/admin/menu'
    | '/admin/pedidos'
    | '/admin/preguntas'
    | '/admin/promociones'
    | '/admin/redes'
    | '/admin/resenas'
    | '/admin/usuarios'
    | '/pedido/$id'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/checkout'
    | '/conozcanos'
    | '/eventos'
    | '/forgot-password'
    | '/horarios'
    | '/login'
    | '/menu'
    | '/mis-pedidos'
    | '/preguntas'
    | '/promociones'
    | '/resenas'
    | '/reservas'
    | '/reset-password'
    | '/sitemap.xml'
    | '/admin/categorias'
    | '/admin/conozcanos'
    | '/admin/eventos'
    | '/admin/filtros'
    | '/admin/horario'
    | '/admin/informacion'
    | '/admin/inicio'
    | '/admin/lenguajes'
    | '/admin/menu'
    | '/admin/pedidos'
    | '/admin/preguntas'
    | '/admin/promociones'
    | '/admin/redes'
    | '/admin/resenas'
    | '/admin/usuarios'
    | '/pedido/$id'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CheckoutRoute: typeof CheckoutRoute
  ConozcanosRoute: typeof ConozcanosRoute
  EventosRoute: typeof EventosRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HorariosRoute: typeof HorariosRoute
  LoginRoute: typeof LoginRoute
  MenuRoute: typeof MenuRoute
  MisPedidosRoute: typeof MisPedidosRoute
  PreguntasRoute: typeof PreguntasRoute
  PromocionesRoute: typeof PromocionesRoute
  ResenasRoute: typeof ResenasRoute
  ReservasRoute: typeof ReservasRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  PedidoIdRoute: typeof PedidoIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reservas': {
      id: '/reservas'
      path: '/reservas'
      fullPath: '/reservas'
      preLoaderRoute: typeof ReservasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resenas': {
      id: '/resenas'
      path: '/resenas'
      fullPath: '/resenas'
      preLoaderRoute: typeof ResenasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/promociones': {
      id: '/promociones'
      path: '/promociones'
      fullPath: '/promociones'
      preLoaderRoute: typeof PromocionesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preguntas': {
      id: '/preguntas'
      path: '/preguntas'
      fullPath: '/preguntas'
      preLoaderRoute: typeof PreguntasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mis-pedidos': {
      id: '/mis-pedidos'
      path: '/mis-pedidos'
      fullPath: '/mis-pedidos'
      preLoaderRoute: typeof MisPedidosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/horarios': {
      id: '/horarios'
      path: '/horarios'
      fullPath: '/horarios'
      preLoaderRoute: typeof HorariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eventos': {
      id: '/eventos'
      path: '/eventos'
      fullPath: '/eventos'
      preLoaderRoute: typeof EventosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conozcanos': {
      id: '/conozcanos'
      path: '/conozcanos'
      fullPath: '/conozcanos'
      preLoaderRoute: typeof ConozcanosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/pedido/$id': {
      id: '/pedido/$id'
      path: '/pedido/$id'
      fullPath: '/pedido/$id'
      preLoaderRoute: typeof PedidoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/usuarios': {
      id: '/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AdminUsuariosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/resenas': {
      id: '/admin/resenas'
      path: '/resenas'
      fullPath: '/admin/resenas'
      preLoaderRoute: typeof AdminResenasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/redes': {
      id: '/admin/redes'
      path: '/redes'
      fullPath: '/admin/redes'
      preLoaderRoute: typeof AdminRedesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/promociones': {
      id: '/admin/promociones'
      path: '/promociones'
      fullPath: '/admin/promociones'
      preLoaderRoute: typeof AdminPromocionesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/preguntas': {
      id: '/admin/preguntas'
      path: '/preguntas'
      fullPath: '/admin/preguntas'
      preLoaderRoute: typeof AdminPreguntasRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/pedidos': {
      id: '/admin/pedidos'
      path: '/pedidos'
      fullPath: '/admin/pedidos'
      preLoaderRoute: typeof AdminPedidosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/menu': {
      id: '/admin/menu'
      path: '/menu'
      fullPath: '/admin/menu'
      preLoaderRoute: typeof AdminMenuRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/lenguajes': {
      id: '/admin/lenguajes'
      path: '/lenguajes'
      fullPath: '/admin/lenguajes'
      preLoaderRoute: typeof AdminLenguajesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inicio': {
      id: '/admin/inicio'
      path: '/inicio'
      fullPath: '/admin/inicio'
      preLoaderRoute: typeof AdminInicioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/informacion': {
      id: '/admin/informacion'
      path: '/informacion'
      fullPath: '/admin/informacion'
      preLoaderRoute: typeof AdminInformacionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/horario': {
      id: '/admin/horario'
      path: '/horario'
      fullPath: '/admin/horario'
      preLoaderRoute: typeof AdminHorarioRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/filtros': {
      id: '/admin/filtros'
      path: '/filtros'
      fullPath: '/admin/filtros'
      preLoaderRoute: typeof AdminFiltrosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/eventos': {
      id: '/admin/eventos'
      path: '/eventos'
      fullPath: '/admin/eventos'
      preLoaderRoute: typeof AdminEventosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/conozcanos': {
      id: '/admin/conozcanos'
      path: '/conozcanos'
      fullPath: '/admin/conozcanos'
      preLoaderRoute: typeof AdminConozcanosRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/categorias': {
      id: '/admin/categorias'
      path: '/categorias'
      fullPath: '/admin/categorias'
      preLoaderRoute: typeof AdminCategoriasRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCategoriasRoute: typeof AdminCategoriasRoute
  AdminConozcanosRoute: typeof AdminConozcanosRoute
  AdminEventosRoute: typeof AdminEventosRoute
  AdminFiltrosRoute: typeof AdminFiltrosRoute
  AdminHorarioRoute: typeof AdminHorarioRoute
  AdminInformacionRoute: typeof AdminInformacionRoute
  AdminInicioRoute: typeof AdminInicioRoute
  AdminLenguajesRoute: typeof AdminLenguajesRoute
  AdminMenuRoute: typeof AdminMenuRoute
  AdminPedidosRoute: typeof AdminPedidosRoute
  AdminPreguntasRoute: typeof AdminPreguntasRoute
  AdminPromocionesRoute: typeof AdminPromocionesRoute
  AdminRedesRoute: typeof AdminRedesRoute
  AdminResenasRoute: typeof AdminResenasRoute
  AdminUsuariosRoute: typeof AdminUsuariosRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCategoriasRoute: AdminCategoriasRoute,
  AdminConozcanosRoute: AdminConozcanosRoute,
  AdminEventosRoute: AdminEventosRoute,
  AdminFiltrosRoute: AdminFiltrosRoute,
  AdminHorarioRoute: AdminHorarioRoute,
  AdminInformacionRoute: AdminInformacionRoute,
  AdminInicioRoute: AdminInicioRoute,
  AdminLenguajesRoute: AdminLenguajesRoute,
  AdminMenuRoute: AdminMenuRoute,
  AdminPedidosRoute: AdminPedidosRoute,
  AdminPreguntasRoute: AdminPreguntasRoute,
  AdminPromocionesRoute: AdminPromocionesRoute,
  AdminRedesRoute: AdminRedesRoute,
  AdminResenasRoute: AdminResenasRoute,
  AdminUsuariosRoute: AdminUsuariosRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CheckoutRoute: CheckoutRoute,
  ConozcanosRoute: ConozcanosRoute,
  EventosRoute: EventosRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HorariosRoute: HorariosRoute,
  LoginRoute: LoginRoute,
  MenuRoute: MenuRoute,
  MisPedidosRoute: MisPedidosRoute,
  PreguntasRoute: PreguntasRoute,
  PromocionesRoute: PromocionesRoute,
  ResenasRoute: ResenasRoute,
  ReservasRoute: ReservasRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  PedidoIdRoute: PedidoIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
